"""
Python wrapper for HTTP-interface of YT system.

Package supports `YT API <https://ytsaurus.tech/docs/en/api/python/start>`_.

Be ready to catch :class:`YtError <yt.common.YtError>` after all commands!
"""

from . import version_check  # noqa

from .client_api import (
    LocalFile,
    PingTransaction,
    TablePath,
    TempTable,
    Transaction,
    _batch_commands,
    abort_job,
    abort_operation,
    abort_query,
    abort_transaction,
    add_maintenance,
    add_member,
    all_names,
    alter_table,
    alter_table_replica,
    balance_tablet_cells,
    batch_apply,
    check_permission,
    commit_transaction,
    complete_operation,
    concatenate,
    copy,
    create,
    create_batch_client,
    create_revision_parameter,
    create_table,
    create_table_backup,
    create_temp_table,
    delete_rows,
    destroy_chunk_locations,
    disable_chunk_locations,
    download_core_dump,
    dump_job_context,
    execute_batch,
    exists,
    explain_query,
    externalize,
    find_free_subpath,
    find_spark_cluster,
    freeze_table,
    generate_timestamp,
    get,
    get_attribute,
    get_current_transaction_id,
    get_file_from_cache,
    get_in_sync_replicas,
    get_job,
    get_job_input,
    get_job_input_paths,
    get_job_spec,
    get_job_stderr,
    get_operation,
    get_operation_attributes,
    get_operation_state,
    get_query,
    get_supported_features,
    get_table_columnar_statistics,
    get_table_schema,
    get_tablet_errors,
    get_tablet_infos,
    get_type,
    get_user_name,
    has_attribute,
    insert_rows,
    internalize,
    is_empty,
    is_sorted,
    issue_token,
    iterate_operations,
    link,
    list,
    list_jobs,
    list_operations,
    list_queries,
    list_queue_consumer_registrations,
    list_user_tokens,
    lock,
    lock_rows,
    lookup_rows,
    mkdir,
    mount_table,
    move,
    ping_transaction,
    put_file_to_cache,
    read_blob_table,
    read_file,
    read_query_result,
    read_table,
    read_table_structured,
    register_queue_consumer,
    remount_table,
    remove,
    remove_attribute,
    remove_maintenance,
    remove_member,
    reshard_table,
    reshard_table_automatic,
    restore_table_backup,
    resume_operation,
    resurrect_chunk_locations,
    revoke_token,
    row_count,
    run_command_with_lock,
    run_erase,
    run_job_shell,
    run_join_reduce,
    run_map,
    run_map_reduce,
    run_merge,
    run_operation,
    run_reduce,
    run_remote_copy,
    run_sort,
    sample_rows_from_table,
    search,
    select_rows,
    set,
    set_attribute,
    set_user_password,
    shuffle_table,
    smart_upload_file,
    start_query,
    start_spark_cluster,
    start_transaction,
    suspend_operation,
    transfer_account_resources,
    transfer_pool_resources,
    transform,
    trim_rows,
    unfreeze_table,
    unlock,
    unmount_table,
    unregister_queue_consumer,
    update_operation_parameters,
    write_file,
    write_table,
    write_table_structured,
)

from .client import YtClient, create_client_with_command_params  # noqa

from .spec_builders import (  # noqa
    JobIOSpecBuilder, PartitionJobIOSpecBuilder, SortJobIOSpecBuilder, MergeJobIOSpecBuilder, ReduceJobIOSpecBuilder,
    MapJobIOSpecBuilder,
    UserJobSpecBuilder, TaskSpecBuilder, MapperSpecBuilder, ReducerSpecBuilder, ReduceCombinerSpecBuilder,
    ReduceSpecBuilder, JoinReduceSpecBuilder, MapSpecBuilder, MapReduceSpecBuilder, MergeSpecBuilder,
    SortSpecBuilder, RemoteCopySpecBuilder, EraseSpecBuilder, VanillaSpecBuilder)
from .errors import (  # noqa
    YtError, YtOperationFailedError, YtResponseError, YtHttpResponseError,
    YtProxyUnavailable, YtTokenError, YtTransactionPingError, YtRequestTimedOut)
from .batch_execution import YtBatchRequestFailedError  # noqa
from .yamr_record import Record  # noqa
from .format import (  # noqa
    DsvFormat, YamrFormat, YsonFormat, JsonFormat, SchemafulDsvFormat, SkiffFormat,
    YamredDsvFormat, Format, create_format, dumps_row, loads_row, YtFormatError, create_table_switch)
from .ypath import YPath, TablePath, FilePath, ypath_join, ypath_dirname, ypath_split, escape_ypath_literal  # noqa
from .operation_commands import format_operation_stderrs, Operation  # noqa
from .prepare_operation import TypedJob  # noqa
from .operations_tracker import OperationsTracker, OperationsTrackerPool  # noqa
from .py_wrapper import (  # noqa
    aggregator, raw, raw_io, reduce_aggregator,
    enable_python_job_processing_for_standalone_binary, initialize_python_job_processing,
    with_context, with_skiff_schemas, respawn_in_docker)
from .schema import yt_dataclass, create_yt_enum, OutputRow  # noqa
from .string_iter_io import StringIterIO  # noqa
from .user_statistics import write_statistics  # noqa
from .yamr_mode import set_yamr_mode  # noqa
from .dynamic_table_commands import ASYNC_LAST_COMMITTED_TIMESTAMP, SYNC_LAST_COMMITTED_TIMESTAMP  # noqa
# COMPAT(ignat)
from .dynamic_table_commands import ASYNC_LAST_COMMITED_TIMESTAMP, SYNC_LAST_COMMITED_TIMESTAMP  # noqa
from .skiff import convert_to_skiff_schema  # noqa
from .http_helpers import get_retriable_errors  # noqa

from .common import get_version, is_inside_job, escape_c  # noqa
__version__ = VERSION = get_version()

# Some useful parts of private API.
from .http_helpers import (  # noqa
    _cleanup_http_session,
    get_token as _get_token,
    get_proxy_url as _get_proxy_url,
    make_request_with_retries as _make_http_request_with_retries)

from . import schema  # noqa

# For PyCharm checks
from . import config  # noqa
from . import default_config  # noqa
from .config import update_config  # noqa

__all__ = [
    "config",
    "default_config",
    "schema",
    "version_check",
    "YtClient",
    "create_client_with_command_params",
    "EraseSpecBuilder",
    "JobIOSpecBuilder",
    "JoinReduceSpecBuilder",
    "MapJobIOSpecBuilder",
    "MapReduceSpecBuilder",
    "MapSpecBuilder",
    "MapperSpecBuilder",
    "MergeJobIOSpecBuilder",
    "MergeSpecBuilder",
    "PartitionJobIOSpecBuilder",
    "ReduceCombinerSpecBuilder",
    "ReduceJobIOSpecBuilder",
    "ReduceSpecBuilder",
    "ReducerSpecBuilder",
    "RemoteCopySpecBuilder",
    "SortJobIOSpecBuilder",
    "SortSpecBuilder",
    "TaskSpecBuilder",
    "UserJobSpecBuilder",
    "VanillaSpecBuilder",
    "YtError",
    "YtHttpResponseError",
    "YtOperationFailedError",
    "YtProxyUnavailable",
    "YtRequestTimedOut",
    "YtResponseError",
    "YtTokenError",
    "YtTransactionPingError",
    "YtBatchRequestFailedError",
    "Record",
    "DsvFormat",
    "Format",
    "JsonFormat",
    "SchemafulDsvFormat",
    "SkiffFormat",
    "YamrFormat",
    "YamredDsvFormat",
    "YsonFormat",
    "YtFormatError",
    "create_format",
    "create_table_switch",
    "dumps_row",
    "loads_row",
    "FilePath",
    "TablePath",
    "YPath",
    "escape_ypath_literal",
    "ypath_dirname",
    "ypath_join",
    "ypath_split",
    "Operation",
    "format_operation_stderrs",
    "TypedJob",
    "OperationsTracker",
    "OperationsTrackerPool",
    "aggregator",
    "enable_python_job_processing_for_standalone_binary",
    "initialize_python_job_processing",
    "raw",
    "raw_io",
    "reduce_aggregator",
    "with_context",
    "with_skiff_schemas",
    "respawn_in_docker",
    "OutputRow",
    "create_yt_enum",
    "yt_dataclass",
    "StringIterIO",
    "write_statistics",
    "set_yamr_mode",
    "ASYNC_LAST_COMMITTED_TIMESTAMP",
    "SYNC_LAST_COMMITTED_TIMESTAMP",
    "ASYNC_LAST_COMMITED_TIMESTAMP",
    "SYNC_LAST_COMMITED_TIMESTAMP",
    "convert_to_skiff_schema",
    "_cleanup_http_session",
    "_get_proxy_url",
    "get_retriable_errors",
    "_get_token",
    "_make_http_request_with_retries",
    "escape_c",
    "get_version",
    "is_inside_job",
    "update_config",
    "search",
    "concatenate",
    "find_free_subpath",
    "create_revision_parameter",
    "get_table_schema",
    "create_temp_table",
    "write_table",
    "read_table",
    "read_blob_table",
    "write_table_structured",
    "read_table_structured",
    "download_core_dump",
    "select_rows",
    "insert_rows",
    "delete_rows",
    "lookup_rows",
    "lock_rows",
    "explain_query",
    "register_queue_consumer",
    "unregister_queue_consumer",
    "list_queue_consumer_registrations",
    "start_query",
    "abort_query",
    "read_query_result",
    "get_query",
    "list_queries",
    "run_erase",
    "run_merge",
    "run_sort",
    "run_map_reduce",
    "run_map",
    "run_reduce",
    "run_join_reduce",
    "run_remote_copy",
    "run_operation",
    "get_operation_state",
    "abort_operation",
    "complete_operation",
    "get_operation",
    "list_operations",
    "iterate_operations",
    "read_file",
    "write_file",
    "smart_upload_file",
    "Transaction",
    "PingTransaction",
    "get_current_transaction_id",
    "create_batch_client",
    "batch_apply",
    "sample_rows_from_table",
    "shuffle_table",
    "TempTable",
    "transform",
    "run_job_shell",
    "get_job_stderr",
    "get_job_input",
    "get_job_input_paths",
    "dump_job_context",
    "list_jobs",
    "get_job",
    "get_job_spec",
    "execute_batch",
    "get_supported_features",
    "TablePath",
    "get_user_name",
    "start_spark_cluster",
    "find_spark_cluster",
    "run_command_with_lock",
    "add_maintenance",
    "remove_maintenance",
    "disable_chunk_locations",
    "destroy_chunk_locations",
    "resurrect_chunk_locations",
    "set_user_password",
    "issue_token",
    "revoke_token",
    "list_user_tokens",
    "all_names",
    "_batch_commands",
    "set",
    "get",
    "list",
    "exists",
    "remove",
    "externalize",
    "internalize",
    "mkdir",
    "copy",
    "move",
    "link",
    "get_type",
    "create",
    "has_attribute",
    "get_attribute",
    "set_attribute",
    "remove_attribute",
    "check_permission",
    "add_member",
    "remove_member",
    "lock",
    "unlock",
    "LocalFile",
    "put_file_to_cache",
    "get_file_from_cache",
    "create_table",
    "row_count",
    "is_sorted",
    "is_empty",
    "alter_table",
    "get_table_columnar_statistics",
    "mount_table",
    "unmount_table",
    "remount_table",
    "freeze_table",
    "unfreeze_table",
    "reshard_table",
    "reshard_table_automatic",
    "balance_tablet_cells",
    "trim_rows",
    "alter_table_replica",
    "get_in_sync_replicas",
    "get_tablet_infos",
    "get_tablet_errors",
    "create_table_backup",
    "restore_table_backup",
    "suspend_operation",
    "resume_operation",
    "get_operation_attributes",
    "update_operation_parameters",
    "get_operation",
    "list_operations",
    "get_job",
    "list_jobs",
    "start_transaction",
    "abort_transaction",
    "commit_transaction",
    "ping_transaction",
    "abort_job",
    "generate_timestamp",
    "transfer_account_resources",
    "transfer_pool_resources",
]
